version: '3.1'

services:
  pgvector-db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vector_db
    ports:
      - "5432:5432"
    volumes:
      - localagent_data:/var/lib/postgresql/data
volumes:
  localagent_data: